package cn.creditease.godzilla.dao;

import cn.creditease.godzilla.model.FunRight;

public interface FunRightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_function_right
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insert(FunRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_function_right
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insertSelective(FunRight record);
}