package cn.creditease.godzilla.dao;

import cn.creditease.godzilla.model.ProjPrivate;

public interface ProjPrivateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_project_private
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insert(ProjPrivate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_project_private
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insertSelective(ProjPrivate record);
}