package cn.creditease.godzilla.dao;

import cn.creditease.godzilla.model.SvnChangeLog;

public interface SvnChangeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_svn_change_logs
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insert(SvnChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_svn_change_logs
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insertSelective(SvnChangeLog record);
}