package cn.creditease.godzilla.dao;

import cn.creditease.godzilla.model.SvnCmdLog;

public interface SvnCmdLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_svn_command_logs
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insert(SvnCmdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_svn_command_logs
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insertSelective(SvnCmdLog record);
}