package cn.creditease.godzilla.dao;

import cn.creditease.godzilla.model.SvnConflict;

public interface SvnConflictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_svn_conflict
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insert(SvnConflict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_svn_conflict
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insertSelective(SvnConflict record);
}