package cn.godzilla.common;

/**
 * 哥斯拉常量
 * @author 201407280166
 *
 */
public interface Constant {
	
	int TRUE = 1;
	int FALSE = 0 ;
	
	String DEFAULT_VERSION_PARENTPOM = "1.0.0-SNAPSHOT";
	String EMPTY_BRANCH = "empty";
	
	String SUCCESS = "SUCCESS";
	String FAILURE = "FAILURE";
	String BUILDFAILURE = "BUILDFAILURE";
	String NOSETPROPS = "NOSETPROPS";
	String AUDITOR_TEXT = "审核通过";
	int DEFAULT_TIMEOUT = 50;//tomcat启动超时时间(second)
	/**
	 * shell command
	 */
	String FILENAME_POM = "/pom.xml";
	String OK_SHELL = "0";
	String BLACKSPACE = " ";
	String SH_COPYWAR_SERVER = "sh /home/godzilla/gzl/shell/server/copywar_server.sh";
	String SAVE_WAR_PATH= "/home/godzilla/gzl/war";
	String WAR_HOME = "/app/tomcat/webapps/*.war";
	String SH_RESTARTTOMCAT_CLIENT = "sh /home/godzilla/gzl/shell/client/restart_client.sh";
	String SH_GODZILLA_SERVER = "sh /home/godzilla/gzl/shell/server/godzilla.sh";
	String SH_MVN_CLIENT = "sh /home/godzilla/gzl/shell/client/godzilla_mvn.sh";
	String COM_DEPLOY = "DEPLOY";
	String COM_SHOWLIB = "SHOWLIB";
	String TOMCAT_HOME = "/app/tomcat";
	String SH_SVN_CLIENT = "sh /home/godzilla/gzl/shell/client/godzilla_svn.sh";
	String COM_COMMIT = "COMMIT";
	//String QUATE = "\"";
	String QUATE = "";
	String COM_COMMIT_RESOLVE = "COMMIT_RESOLVE";
	String COM_RESOLVE = "RESOLVE";
	String COM_MERGE = "MERGE";
	String COM_MERGE_RESOLVE = "MERGE_RESOLVE";
	String COM_INFO = "INFO";
	String COM_VERSION = "VERSION";
	/**  svn mergestatus 0:无 1:有冲突 2:标记解决 */
	String NO_CONFLICT = "0";
	String HAS_CONFLICT = "1";/**  svn mergestatus 0:无 1:有冲突 2:标记解决 */
	String OK_RESOLVED = "2";/**  svn mergestatus 0:无 1:有冲突 2:标记解决 */
	/**
	 * userservice 连接客户端
	 */
	String SERVER_USER = "new-manager";
	/**
	 * log constant
	 */
	int SUCC = 1;
	int FAIL = -2;
	String DEPLOY = "DEPLOY";
	String SRCEDIT = "SRCEDIT";
	String UPDATEPROP = "UPDATEPROP";
	String VERIFYPROP = "VERIFYPROP";
	String SORTPROP = "SORTPROP";
	String BRANCHADD = "BRANCHADD";
	String BRANCHEDIT = "BRANCHEDIT";
	String BRANCHDELETE = "BRANCHDELETE";
	String SVNSTATUS = "SVNSTATUS";
	String SVNMERGE = "SVNMERGE";
	String SVNCOMMIT = "SVNCOMMIT";
	String TOMCATRESTART = "TOMCATRESTART";
	String SSHCOPYWAR = "SSHCOPYWAR";
	String WARDOWNLOAD= "WARDOWNLOAD";
	String GODZILLAEX= "GODZILLAEX";
	String ADMINOPERATOR= "ADMINOPERATOR";
	String EDITWORKDESK = "EDITWORKDESK";
	String ADDUSER = "ADDUSER";
	String LOGIN = "LOGIN";
	String SHOWDEPLOYLOG = "SHOWDEPLOYLOG";
	String SHOWWARINFO = "SHOWWARINFO";
	String CONFLICTRESOLVED = "CONFLICTRESOLVED";
	String CHANGEPASSWD = "CHANGEPASSWD";
	String RPCEX = "RPCEX";
	
	String NOTYET_VERIFY_STATUS = "0";//未审核
	String OK_VERIFY_STATUS = "1";//审核通过
	String STOP_VERIFY_STATUS = "2";//未通过
	String PROJECT_ENV = "test";
	String SHELL_SERVER_PATH = "/home/godzilla/gzl/shell/server";
	String SHELL_CLIENT_PATH = "/home/godzilla/gzl/shell/client";
	
	/**
	 * freemarker ftl url base path
	 */
	String BASE_PATH = "godzilla-web";
	
	
	String TEST_PROFILE = "TEST";
	String QUASIPRODUCT_PROFILE = "QUASIPRODUCT";
	String PRODUCT_PROFILE = "PRODUCT";
	/**
	 * echo default value
	 */
	int DEFAULT_WEBSOCKET_PORT = 9999;
	String DEFAULT_MQ_PRODUCER_NAME = "godzilla-producer";
	String DEFAULT_MQ_CONSUMER_NAME = "godzilla-consumer";
	String DEFAULT_MQ_NAMESRV_ADDR = "10.100.142.65:9876";
	String DEFAULT_MQ_TOPIC = "godzilla";
	/**
	 * rpc default value
	 */
	String DEFAULT_POM_BASEPATH = "/home/godzilla/gzl/work/godzilla";
	
	/**
	 * echo KEY NAME 
	 */
	String WEBSOCKET_PORT_KEY = "websocket.port";
	String MQ_PRODUCER_NAME_KEY = "rocketmq.producer.name";
	String MQ_CONSUMER_NAME_KEY = "rocketmq.consumer.name";
	String MQ_NAMESRV_ADDR_KEY = "rocketmq.nameserver.address";
	String MQ_TOPIC_KEY = "rocketmq.topic";
	
	/**
	 * rpc KEY NAME 
	 */
	String POM_BASEPATH_KEY = "rpc.pom.basepath";
	
	String NO_AJAX = "NO_AJAX";
	String NULL_NAMEPASSWORD = "NULL_NAMEPASSWORD";
	String NOTEXIST_USER = "NOTEXIST_USER";
	String WRONG_PASSWORD = "WRONG_PASSWORD";
	String UNKNOW_ERROR = "UNKNOW_ERROR";
	String NO_LOGIN = "NO_LOGIN";
	String NO_ADDUPDATEPROP = "NO_ADDUPDATEPROP";
	String NO_VERIFYPROP = "NO_VERIFYPROP";
	String NO_AUTHORITY = "NO_AUTHORITY";
	//String NO_MVNDEPLOY = "NO_MVNDEPLOY";
	String NO_CHANGEPOM = "NO_CHANGEPOM";
	String NO_RPCFACTORY = "NO_RPCFACTORY";
	String NO_AUTHORIZATION = "NO_AUTHORIZATION";
	String NO_ADDUSER = "NO_ADDUSER";
	String NO_SAMEPASSWORD = "NO_SAMEPASSWORD";
	String NO_UPDATEFUNRIGHT = "NO_UPDATEFUNRIGHT";
	String NO_CHANGECOMMIT = "NO_CHANGECOMMIT";
	String NO_SVNCOMMIT = "NO_SVNCOMMIT";
	String NO_FOUNDCONFLICT = "NO_FOUNDCONFLICT";
	String NO_CLIENTPARAM = "NO_CLIENTPARAM";
	String NO_SERVERPARAM = "NO_SERVERPARAM";
	String NO_JAVASHELLCALL = "NO_JAVASHELLCALL";
	String NO_SVNVERSION = "NO_SVNVERSION";
	String NO_GODZILLA = "NO_GODZILLA";
	String NO_DELETEBRANCH = "NO_DELETEBRANCH";
	String NO_SVNMERGE = "NO_SVNMERGE";
	String NO_MVNBUILD = "NO_MVNBUILD";
	String NO_COMMON = "NO_COMMON";
	String NO_CONCURRENCEDEPLOY = "NO_CONCURRENCEDEPLOY";
	String NO_MVNSETPROPS = "NO_MVNSETPROPS";
	String NO_HASKEYDEPLOY = "NO_HASKEYDEPLOY";
	String NO_EXISTUSER = "NO_EXISTUSER";
	String NO_STARTTOMCAT = "NO_STARTTOMCAT";
	String NO_SRCEDIT = "NO_SRCEDIT";
	String NO_BRANCHADD = "NO_BRANCHADD";
	String NO_SVNSTATUS = "NO_SVNSTATUS";
	String NO_SHOWWARINFO = "NO_SHOWWARINFO";
	String NO_SHOWDEPLOYLOG = "NO_SHOWDEPLOYLOG";
	String NO_RESTARTTOMCAT = "NO_RESTARTTOMCAT";
	String NO_MVNBUILDLOG = "NO_MVNBUILDLOG";
	String NO_DEPLOYLOGID = "NO_DEPLOYLOGID";
	String NO_STOREDEPLOYLOG = "NO_STOREDEPLOYLOG";
	String NO_SHOWWARINFOID = "NO_SHOWWARINFOID";
	String NO_RESTARTEFFECT = "NO_RESTARTEFFECT";
	String NO_INTERRUPTEDEX = "NO_INTERRUPTEDEX";
	String NO_SYSTEMEX = "NO_SYSTEMEX";
	String NO_RPCEX = "NO_RPCEX";
	String NO_SVNEDIT = "NO_SVNEDIT";
	String NO_EDITMERGESTATUS = "NO_EDITMERGESTATUS";
	String NO_SVNRESOLVED = "NO_SVNRESOLVED";
	String NO_ERRORCOMMAND = "NO_ERRORCOMMAND";
	String NO_STILLHASCONFLICTBRANCH = "NO_STILLHASCONFLICTBRANCH";
	String NO_HAVEBRANCHES = "NO_HAVEBRANCHES";
	String NO_FOUNDNEWCONFLICT = "NO_FOUNDNEWCONFLICT";
	String NO_SVNRESOLVE = "NO_SVNRESOLVE";
	String NO_NEWCONFLICTFOUND = "NO_NEWCONFLICTFOUND";
	String NO_WRONGOLDPWD = "NO_WRONGOLDPWD";
	String NO_CHANGEPWD = "NO_CHANGEPWD";
	String NO_LOOSEPROP = "NO_LOOSEPROP";
	String NO_NEEDRESOLVE = "NO_NEEDRESOLVE";
	
	String OK_AJAX = "OK_AJAX";
	String OK_CHECKUSER = "OK_CHECKUSER";
	String OK_LOGIN = "OK_LOGIN";
	String OK_ADDUPDATEPROP = "OK_ADDUPDATEPROP";
	String OK_VERIFYPROP = "OK_VERIFYPROP";
	String OK_MVNDEPLOY = "OK_MVNDEPLOY";
	String OK_CHANGEPOM = "OK_CHANGEPOM";
	String OK_AUTHORIZATION = "OK_AUTHORIZATION";
	String OK_ADDUSER = "OK_ADDUSER";
	String OK_UPDATEFUNRIGHT = "OK_SVNCOMMIT";
	String OK_SVNCOMMIT = "OK_SVNCOMMIT";
	String OK_SVNVERSION = "OK_SVNVERSION";
	String OK_SORTPROP = "OK_SORTPROP";
	String OK_GODZILLA = "OK_GODZILLA";
	String OK_DELETEBRANCH = "OK_DELETEBRANCH";
	String OK_SVNMERGE = "OK_SVNMERGE";
	String OK_MVNBUILD = "OK_MVNBUILD";
	String OK_STARTTOMCAT = "OK_STARTTOMCAT";
	String OK_SRCEDIT = "OK_SRCEDIT";
	String OK_BRANCHADD = "OK_BRANCHADD";
	String OK_SVNSTATUS = "OK_SVNSTATUS";
	String OK_SHOWWARINFO = "OK_SHOWWARINFO";
	String OK_SHOWDEPLOYLOG = "OK_SHOWDEPLOYLOG";
	String OK_QUERYPERCENT = "OK_QUERYPERCENT";
	String OK_SVNEDIT = "OK_SVNEDIT";
	String OK_EDITMERGESTATUS = "OK_EDITMERGESTATUS";
	String OK_SVNRESOLVED = "OK_SVNRESOLVED";
	String OK_CHANGEPWD = "OK_CHANGEPWD";
	
	/*String NO_AJAX = "100000";
	String NULL_NAMEPASSWORD = "100001";
	String NOTEXIST_USER = "100002";
	String WRONG_PASSWORD = "100003";
	String UNKNOW_ERROR = "100004";
	String NO_LOGIN = "100005";
	String NO_ADDUPDATEPROP = "100011";
	String NO_VERIFYPROP = "100012";
	String NO_AUTHORITY = "100013";
	//String NO_MVNDEPLOY = "100014";
	String NO_CHANGEPOM = "100015";
	String NO_RPCFACTORY = "100016";
	String NO_AUTHORIZATION = "100017";
	String NO_ADDUSER = "100019";
	String NO_SAMEPASSWORD = "100019";
	String NO_UPDATEFUNRIGHT = "100020";
	String NO_CHANGECOMMIT = "100021";
	String NO_SVNCOMMIT = "100022";
	String NO_FOUNDCONFLICT = "100023";
	String NO_CLIENTPARAM = "100024";
	String NO_SERVERPARAM = "100025";
	String NO_JAVASHELLCALL = "100026";
	String NO_SVNVERSION = "100027";
	String NO_GODZILLA = "100029";
	String NO_DELETEBRANCH = "100030";
	String NO_SVNMERGE = "100031";
	String NO_MVNBUILD = "100032";
	String NO_COMMON = "100033";
	String NO_CONCURRENCEDEPLOY = "100034";
	String NO_MVNSETPROPS = "100035";
	String NO_HASKEYDEPLOY = "100036";
	String NO_EXISTUSER = "100037";
	String NO_STARTTOMCAT = "100038";
	String NO_SRCEDIT = "100039";
	String NO_BRANCHADD = "100040";
	String NO_SVNSTATUS = "100041";
	String NO_SHOWWARINFO = "100042";
	String NO_SHOWDEPLOYLOG = "100043";
	String NO_RESTARTTOMCAT = "100044";
	String NO_MVNBUILDLOG = "100045";
	String NO_DEPLOYLOGID = "100046";
	String NO_STOREDEPLOYLOG = "100047";
	String NO_SHOWWARINFOID = "100048";
	String NO_RESTARTEFFECT = "100049";
	String NO_INTERRUPTEDEX = "100050";
	String NO_SYSTEMEX = "100051";
	String NO_RPCEX = "100052";
	String NO_SVNEDIT = "100054";
	String NO_EDITMERGESTATUS = "100055";
	String NO_SVNRESOLVED = "100056";
	String NO_ERRORCOMMAND = "100057";
	String NO_STILLHASCONFLICTBRANCH = "100058";
	String NO_HAVEBRANCHES = "100059";
	String NO_FOUNDNEWCONFLICT = "100060";
	String NO_SVNRESOLVE = "100061";
	String NO_NEWCONFLICTFOUND = "100062";
	String NO_WRONGOLDPWD = "100063";
	String NO_CHANGEPWD = "100064";
	String NO_LOOSEPROP = "100065";
	String NO_NEEDRESOLVE = "100066";
	
	String OK_AJAX = "200000";
	String OK_CHECKUSER = "200001";
	String OK_LOGIN = "200002";
	String OK_ADDUPDATEPROP = "200011";
	String OK_VERIFYPROP = "200012";
	String OK_MVNDEPLOY = "200014";
	String OK_CHANGEPOM = "200015";
	String OK_AUTHORIZATION = "200017";
	String OK_ADDUSER = "200018";
	String OK_UPDATEFUNRIGHT = "200020";
	String OK_SVNCOMMIT = "200021";
	String OK_SVNVERSION = "200027";
	String OK_SORTPROP = "200028";
	String OK_GODZILLA = "200029";
	String OK_DELETEBRANCH = "200030";
	String OK_SVNMERGE = "200031";
	String OK_MVNBUILD = "200032";
	String OK_STARTTOMCAT = "200038";
	String OK_SRCEDIT = "200039";
	String OK_BRANCHADD = "200040";
	String OK_SVNSTATUS = "200041";
	String OK_SHOWWARINFO = "200042";
	String OK_SHOWDEPLOYLOG = "200043";
	String OK_QUERYPERCENT = "200053";
	String OK_SVNEDIT = "200054";
	String OK_EDITMERGESTATUS = "200055";
	String OK_SVNRESOLVED = "200061";
	String OK_CHANGEPWD = "200064";*/
	
	
}
