package cn.creditease.godzilla.model;

public class MvnCmdLogWithBLOBs extends MvnCmdLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_maven_command_logs.commands
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String commands;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_maven_command_logs.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String resultInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_maven_command_logs.commands
     *
     * @return the value of t_g_maven_command_logs.commands
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getCommands() {
        return commands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_maven_command_logs.commands
     *
     * @param commands the value for t_g_maven_command_logs.commands
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setCommands(String commands) {
        this.commands = commands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_maven_command_logs.result_info
     *
     * @return the value of t_g_maven_command_logs.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getResultInfo() {
        return resultInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_maven_command_logs.result_info
     *
     * @param resultInfo the value for t_g_maven_command_logs.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setResultInfo(String resultInfo) {
        this.resultInfo = resultInfo;
    }
}