package cn.godzilla.model;

public class PropBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties_bill.id
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties_bill.createby
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties_bill.project_code
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties_bill.profile
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    private String profile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties_bill.status
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties_bill.auditor_text
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    private String auditorText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties_bill.id
     *
     * @return the value of properties_bill.id
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties_bill.id
     *
     * @param id the value for properties_bill.id
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties_bill.createby
     *
     * @return the value of properties_bill.createby
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties_bill.createby
     *
     * @param createby the value for properties_bill.createby
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties_bill.project_code
     *
     * @return the value of properties_bill.project_code
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties_bill.project_code
     *
     * @param projectCode the value for properties_bill.project_code
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties_bill.profile
     *
     * @return the value of properties_bill.profile
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties_bill.profile
     *
     * @param profile the value for properties_bill.profile
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties_bill.status
     *
     * @return the value of properties_bill.status
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties_bill.status
     *
     * @param status the value for properties_bill.status
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties_bill.auditor_text
     *
     * @return the value of properties_bill.auditor_text
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public String getAuditorText() {
        return auditorText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties_bill.auditor_text
     *
     * @param auditorText the value for properties_bill.auditor_text
     *
     * @mbggenerated Sat Oct 31 16:41:34 CST 2015
     */
    public void setAuditorText(String auditorText) {
        this.auditorText = auditorText;
    }
}