package cn.godzilla.model;

import java.util.Date;

public class SvnConflict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svn_conflict.id
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svn_conflict.project_code
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svn_conflict.profile
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    private String profile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svn_conflict.create_time
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svn_conflict.creator
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svn_conflict.conflict_path
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    private String conflictPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svn_conflict.version
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column svn_conflict.conflict_files
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    private String conflictFiles;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svn_conflict.id
     *
     * @return the value of svn_conflict.id
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svn_conflict.id
     *
     * @param id the value for svn_conflict.id
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svn_conflict.project_code
     *
     * @return the value of svn_conflict.project_code
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svn_conflict.project_code
     *
     * @param projectCode the value for svn_conflict.project_code
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svn_conflict.profile
     *
     * @return the value of svn_conflict.profile
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svn_conflict.profile
     *
     * @param profile the value for svn_conflict.profile
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svn_conflict.create_time
     *
     * @return the value of svn_conflict.create_time
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svn_conflict.create_time
     *
     * @param createTime the value for svn_conflict.create_time
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svn_conflict.creator
     *
     * @return the value of svn_conflict.creator
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svn_conflict.creator
     *
     * @param creator the value for svn_conflict.creator
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svn_conflict.conflict_path
     *
     * @return the value of svn_conflict.conflict_path
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public String getConflictPath() {
        return conflictPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svn_conflict.conflict_path
     *
     * @param conflictPath the value for svn_conflict.conflict_path
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public void setConflictPath(String conflictPath) {
        this.conflictPath = conflictPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svn_conflict.version
     *
     * @return the value of svn_conflict.version
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svn_conflict.version
     *
     * @param version the value for svn_conflict.version
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column svn_conflict.conflict_files
     *
     * @return the value of svn_conflict.conflict_files
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public String getConflictFiles() {
        return conflictFiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column svn_conflict.conflict_files
     *
     * @param conflictFiles the value for svn_conflict.conflict_files
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    public void setConflictFiles(String conflictFiles) {
        this.conflictFiles = conflictFiles;
    }
}