package cn.godzilla.model;

public class SvnConflict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_conflict.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_conflict.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_conflict.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_conflict.branch_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String branchUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_conflict.trunk_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String trunkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_conflict.file_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_conflict.status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_conflict.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String resultInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_conflict.id
     *
     * @return the value of t_g_svn_conflict.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_conflict.id
     *
     * @param id the value for t_g_svn_conflict.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_conflict.user_name
     *
     * @return the value of t_g_svn_conflict.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_conflict.user_name
     *
     * @param userName the value for t_g_svn_conflict.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_conflict.project_code
     *
     * @return the value of t_g_svn_conflict.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_conflict.project_code
     *
     * @param projectCode the value for t_g_svn_conflict.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_conflict.branch_url
     *
     * @return the value of t_g_svn_conflict.branch_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getBranchUrl() {
        return branchUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_conflict.branch_url
     *
     * @param branchUrl the value for t_g_svn_conflict.branch_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setBranchUrl(String branchUrl) {
        this.branchUrl = branchUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_conflict.trunk_url
     *
     * @return the value of t_g_svn_conflict.trunk_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getTrunkUrl() {
        return trunkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_conflict.trunk_url
     *
     * @param trunkUrl the value for t_g_svn_conflict.trunk_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setTrunkUrl(String trunkUrl) {
        this.trunkUrl = trunkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_conflict.file_name
     *
     * @return the value of t_g_svn_conflict.file_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_conflict.file_name
     *
     * @param fileName the value for t_g_svn_conflict.file_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_conflict.status
     *
     * @return the value of t_g_svn_conflict.status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_conflict.status
     *
     * @param status the value for t_g_svn_conflict.status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_conflict.result_info
     *
     * @return the value of t_g_svn_conflict.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getResultInfo() {
        return resultInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_conflict.result_info
     *
     * @param resultInfo the value for t_g_svn_conflict.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setResultInfo(String resultInfo) {
        this.resultInfo = resultInfo;
    }
}