package cn.creditease.godzilla.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_user.id
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_user.user_name
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_user.password
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_user.real_name
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_user.create_time
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_user.create_by
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_user.status
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_user.login_time
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_user.last_login_time
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_user.depart_name
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    private String departName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_user.is_admin
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    private Integer isAdmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_user.id
     *
     * @return the value of t_g_user.id
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_user.id
     *
     * @param id the value for t_g_user.id
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_user.user_name
     *
     * @return the value of t_g_user.user_name
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_user.user_name
     *
     * @param userName the value for t_g_user.user_name
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_user.password
     *
     * @return the value of t_g_user.password
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_user.password
     *
     * @param password the value for t_g_user.password
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_user.real_name
     *
     * @return the value of t_g_user.real_name
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_user.real_name
     *
     * @param realName the value for t_g_user.real_name
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_user.create_time
     *
     * @return the value of t_g_user.create_time
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_user.create_time
     *
     * @param createTime the value for t_g_user.create_time
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_user.create_by
     *
     * @return the value of t_g_user.create_by
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_user.create_by
     *
     * @param createBy the value for t_g_user.create_by
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_user.status
     *
     * @return the value of t_g_user.status
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_user.status
     *
     * @param status the value for t_g_user.status
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_user.login_time
     *
     * @return the value of t_g_user.login_time
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_user.login_time
     *
     * @param loginTime the value for t_g_user.login_time
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_user.last_login_time
     *
     * @return the value of t_g_user.last_login_time
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_user.last_login_time
     *
     * @param lastLoginTime the value for t_g_user.last_login_time
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_user.depart_name
     *
     * @return the value of t_g_user.depart_name
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_user.depart_name
     *
     * @param departName the value for t_g_user.depart_name
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public void setDepartName(String departName) {
        this.departName = departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_user.is_admin
     *
     * @return the value of t_g_user.is_admin
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public Integer getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_user.is_admin
     *
     * @param isAdmin the value for t_g_user.is_admin
     *
     * @mbggenerated Tue Jun 16 12:01:28 CST 2015
     */
    public void setIsAdmin(Integer isAdmin) {
        this.isAdmin = isAdmin;
    }
}