package cn.creditease.godzilla.model;

import java.util.Date;

public class MvnCmdLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_maven_command_logs.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_maven_command_logs.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_maven_command_logs.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_maven_command_logs.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_maven_command_logs.id
     *
     * @return the value of t_g_maven_command_logs.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_maven_command_logs.id
     *
     * @param id the value for t_g_maven_command_logs.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_maven_command_logs.user_name
     *
     * @return the value of t_g_maven_command_logs.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_maven_command_logs.user_name
     *
     * @param userName the value for t_g_maven_command_logs.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_maven_command_logs.project_code
     *
     * @return the value of t_g_maven_command_logs.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_maven_command_logs.project_code
     *
     * @param projectCode the value for t_g_maven_command_logs.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_maven_command_logs.create_time
     *
     * @return the value of t_g_maven_command_logs.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_maven_command_logs.create_time
     *
     * @param createTime the value for t_g_maven_command_logs.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}