package cn.creditease.godzilla.model;

import java.util.Date;

public class OperateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_operate_logs.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_operate_logs.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_operate_logs.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_operate_logs.profile
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String profile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_operate_logs.operate_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Integer operateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_operate_logs.execute_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Date executeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_operate_logs.execute_result
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Integer executeResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_operate_logs.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String resultInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_operate_logs.id
     *
     * @return the value of t_g_operate_logs.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_operate_logs.id
     *
     * @param id the value for t_g_operate_logs.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_operate_logs.user_name
     *
     * @return the value of t_g_operate_logs.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_operate_logs.user_name
     *
     * @param userName the value for t_g_operate_logs.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_operate_logs.project_code
     *
     * @return the value of t_g_operate_logs.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_operate_logs.project_code
     *
     * @param projectCode the value for t_g_operate_logs.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_operate_logs.profile
     *
     * @return the value of t_g_operate_logs.profile
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_operate_logs.profile
     *
     * @param profile the value for t_g_operate_logs.profile
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_operate_logs.operate_code
     *
     * @return the value of t_g_operate_logs.operate_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Integer getOperateCode() {
        return operateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_operate_logs.operate_code
     *
     * @param operateCode the value for t_g_operate_logs.operate_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setOperateCode(Integer operateCode) {
        this.operateCode = operateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_operate_logs.execute_time
     *
     * @return the value of t_g_operate_logs.execute_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Date getExecuteTime() {
        return executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_operate_logs.execute_time
     *
     * @param executeTime the value for t_g_operate_logs.execute_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setExecuteTime(Date executeTime) {
        this.executeTime = executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_operate_logs.execute_result
     *
     * @return the value of t_g_operate_logs.execute_result
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Integer getExecuteResult() {
        return executeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_operate_logs.execute_result
     *
     * @param executeResult the value for t_g_operate_logs.execute_result
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setExecuteResult(Integer executeResult) {
        this.executeResult = executeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_operate_logs.result_info
     *
     * @return the value of t_g_operate_logs.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getResultInfo() {
        return resultInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_operate_logs.result_info
     *
     * @param resultInfo the value for t_g_operate_logs.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setResultInfo(String resultInfo) {
        this.resultInfo = resultInfo;
    }
}