package cn.creditease.godzilla.model;

import java.util.Date;

public class ProjStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_status_history.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_status_history.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_status_history.current_status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Integer currentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_status_history.process_rate
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Integer processRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_status_history.operate_staff
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String operateStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_status_history.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_status_history.update_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_status_history.finish_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_status_history.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String resultInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_status_history.id
     *
     * @return the value of t_g_project_status_history.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_status_history.id
     *
     * @param id the value for t_g_project_status_history.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_status_history.project_code
     *
     * @return the value of t_g_project_status_history.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_status_history.project_code
     *
     * @param projectCode the value for t_g_project_status_history.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_status_history.current_status
     *
     * @return the value of t_g_project_status_history.current_status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Integer getCurrentStatus() {
        return currentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_status_history.current_status
     *
     * @param currentStatus the value for t_g_project_status_history.current_status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setCurrentStatus(Integer currentStatus) {
        this.currentStatus = currentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_status_history.process_rate
     *
     * @return the value of t_g_project_status_history.process_rate
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Integer getProcessRate() {
        return processRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_status_history.process_rate
     *
     * @param processRate the value for t_g_project_status_history.process_rate
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProcessRate(Integer processRate) {
        this.processRate = processRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_status_history.operate_staff
     *
     * @return the value of t_g_project_status_history.operate_staff
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getOperateStaff() {
        return operateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_status_history.operate_staff
     *
     * @param operateStaff the value for t_g_project_status_history.operate_staff
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setOperateStaff(String operateStaff) {
        this.operateStaff = operateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_status_history.create_time
     *
     * @return the value of t_g_project_status_history.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_status_history.create_time
     *
     * @param createTime the value for t_g_project_status_history.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_status_history.update_time
     *
     * @return the value of t_g_project_status_history.update_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_status_history.update_time
     *
     * @param updateTime the value for t_g_project_status_history.update_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_status_history.finish_time
     *
     * @return the value of t_g_project_status_history.finish_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_status_history.finish_time
     *
     * @param finishTime the value for t_g_project_status_history.finish_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_status_history.result_info
     *
     * @return the value of t_g_project_status_history.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getResultInfo() {
        return resultInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_status_history.result_info
     *
     * @param resultInfo the value for t_g_project_status_history.result_info
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setResultInfo(String resultInfo) {
        this.resultInfo = resultInfo;
    }
}