package cn.creditease.godzilla.model;

public class ProjPrivate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_private.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_private.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_private.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project_private.virtual_truck_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String virtualTruckUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_private.id
     *
     * @return the value of t_g_project_private.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_private.id
     *
     * @param id the value for t_g_project_private.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_private.user_name
     *
     * @return the value of t_g_project_private.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_private.user_name
     *
     * @param userName the value for t_g_project_private.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_private.project_code
     *
     * @return the value of t_g_project_private.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_private.project_code
     *
     * @param projectCode the value for t_g_project_private.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project_private.virtual_truck_url
     *
     * @return the value of t_g_project_private.virtual_truck_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getVirtualTruckUrl() {
        return virtualTruckUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project_private.virtual_truck_url
     *
     * @param virtualTruckUrl the value for t_g_project_private.virtual_truck_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setVirtualTruckUrl(String virtualTruckUrl) {
        this.virtualTruckUrl = virtualTruckUrl;
    }
}