package cn.creditease.godzilla.model;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project.project_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project.repository_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String repositoryUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project.create_by
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project.manager
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_project.status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project.id
     *
     * @return the value of t_g_project.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project.id
     *
     * @param id the value for t_g_project.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project.project_code
     *
     * @return the value of t_g_project.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project.project_code
     *
     * @param projectCode the value for t_g_project.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project.project_name
     *
     * @return the value of t_g_project.project_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project.project_name
     *
     * @param projectName the value for t_g_project.project_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project.repository_url
     *
     * @return the value of t_g_project.repository_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getRepositoryUrl() {
        return repositoryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project.repository_url
     *
     * @param repositoryUrl the value for t_g_project.repository_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setRepositoryUrl(String repositoryUrl) {
        this.repositoryUrl = repositoryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project.create_by
     *
     * @return the value of t_g_project.create_by
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project.create_by
     *
     * @param createBy the value for t_g_project.create_by
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project.manager
     *
     * @return the value of t_g_project.manager
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project.manager
     *
     * @param manager the value for t_g_project.manager
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setManager(String manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_project.status
     *
     * @return the value of t_g_project.status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_project.status
     *
     * @param status the value for t_g_project.status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}