package cn.creditease.godzilla.model;

import java.util.Date;

public class PropConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.profile
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String profile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.pro_key
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String proKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.pro_value
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String proValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.remark
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.create_by
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.update_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.last_value
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String lastValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.auditor
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_properties_config.auditor_text
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String auditorText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.id
     *
     * @return the value of t_g_properties_config.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.id
     *
     * @param id the value for t_g_properties_config.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.project_code
     *
     * @return the value of t_g_properties_config.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.project_code
     *
     * @param projectCode the value for t_g_properties_config.project_code
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.profile
     *
     * @return the value of t_g_properties_config.profile
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.profile
     *
     * @param profile the value for t_g_properties_config.profile
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.pro_key
     *
     * @return the value of t_g_properties_config.pro_key
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProKey() {
        return proKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.pro_key
     *
     * @param proKey the value for t_g_properties_config.pro_key
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProKey(String proKey) {
        this.proKey = proKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.pro_value
     *
     * @return the value of t_g_properties_config.pro_value
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getProValue() {
        return proValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.pro_value
     *
     * @param proValue the value for t_g_properties_config.pro_value
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setProValue(String proValue) {
        this.proValue = proValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.remark
     *
     * @return the value of t_g_properties_config.remark
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.remark
     *
     * @param remark the value for t_g_properties_config.remark
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.create_by
     *
     * @return the value of t_g_properties_config.create_by
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.create_by
     *
     * @param createBy the value for t_g_properties_config.create_by
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.create_time
     *
     * @return the value of t_g_properties_config.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.create_time
     *
     * @param createTime the value for t_g_properties_config.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.update_time
     *
     * @return the value of t_g_properties_config.update_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.update_time
     *
     * @param updateTime the value for t_g_properties_config.update_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.last_value
     *
     * @return the value of t_g_properties_config.last_value
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getLastValue() {
        return lastValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.last_value
     *
     * @param lastValue the value for t_g_properties_config.last_value
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setLastValue(String lastValue) {
        this.lastValue = lastValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.status
     *
     * @return the value of t_g_properties_config.status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.status
     *
     * @param status the value for t_g_properties_config.status
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.auditor
     *
     * @return the value of t_g_properties_config.auditor
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.auditor
     *
     * @param auditor the value for t_g_properties_config.auditor
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_properties_config.auditor_text
     *
     * @return the value of t_g_properties_config.auditor_text
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getAuditorText() {
        return auditorText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_properties_config.auditor_text
     *
     * @param auditorText the value for t_g_properties_config.auditor_text
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setAuditorText(String auditorText) {
        this.auditorText = auditorText;
    }
}