package cn.creditease.godzilla.model;

import java.util.Date;

public class SvnCmdLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_command_logs.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_command_logs.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_command_logs.repository_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String repositoryUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_command_logs.commands
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String commands;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_command_logs.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_g_svn_command_logs.real_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    private String realName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_command_logs.id
     *
     * @return the value of t_g_svn_command_logs.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_command_logs.id
     *
     * @param id the value for t_g_svn_command_logs.id
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_command_logs.user_name
     *
     * @return the value of t_g_svn_command_logs.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_command_logs.user_name
     *
     * @param userName the value for t_g_svn_command_logs.user_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_command_logs.repository_url
     *
     * @return the value of t_g_svn_command_logs.repository_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getRepositoryUrl() {
        return repositoryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_command_logs.repository_url
     *
     * @param repositoryUrl the value for t_g_svn_command_logs.repository_url
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setRepositoryUrl(String repositoryUrl) {
        this.repositoryUrl = repositoryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_command_logs.commands
     *
     * @return the value of t_g_svn_command_logs.commands
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getCommands() {
        return commands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_command_logs.commands
     *
     * @param commands the value for t_g_svn_command_logs.commands
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setCommands(String commands) {
        this.commands = commands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_command_logs.create_time
     *
     * @return the value of t_g_svn_command_logs.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_command_logs.create_time
     *
     * @param createTime the value for t_g_svn_command_logs.create_time
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_g_svn_command_logs.real_name
     *
     * @return the value of t_g_svn_command_logs.real_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_g_svn_command_logs.real_name
     *
     * @param realName the value for t_g_svn_command_logs.real_name
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }
}