# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:/app/maven/bin/:.
JAVA_HOME=/opt/jdk1.7.0_71

export JAVA_HOME
export PATH
