package cn.godzilla.dao;

import cn.godzilla.model.MvnCmdLogWithBLOBs;

public interface MvnCmdLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_maven_command_logs
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insert(MvnCmdLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_maven_command_logs
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insertSelective(MvnCmdLogWithBLOBs record);
}