package cn.godzilla.dao;

import cn.godzilla.model.OperateLog;

public interface OperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_operate_logs
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insert(OperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_operate_logs
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insertSelective(OperateLog record);
}