package cn.godzilla.dao;

import cn.godzilla.model.Project;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_project
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_project
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insertSelective(Project record);
}