package cn.godzilla.dao;

import cn.godzilla.model.ProjStatus;

public interface ProjStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_project_status_history
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insert(ProjStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_project_status_history
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insertSelective(ProjStatus record);
}