package cn.creditease.godzilla.dao;

import cn.creditease.godzilla.model.PropConfig;

public interface PropConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_properties_config
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insert(PropConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_properties_config
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insertSelective(PropConfig record);
}