package cn.godzilla.dao;

import cn.godzilla.model.SvnConflict;

public interface SvnConflictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svn_conflict
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svn_conflict
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    int insert(SvnConflict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svn_conflict
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    int insertSelective(SvnConflict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svn_conflict
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    SvnConflict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svn_conflict
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    int updateByPrimaryKeySelective(SvnConflict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svn_conflict
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(SvnConflict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svn_conflict
     *
     * @mbggenerated Tue Nov 03 14:12:36 CST 2015
     */
    int updateByPrimaryKey(SvnConflict record);

}