package cn.godzilla.dao;

import java.util.List;
import java.util.Map;

import cn.godzilla.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_user
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_user
     *
     * @mbggenerated Wed Jun 10 19:29:50 CST 2015
     */
    int insertSelective(User record);

	User queryUserByUsername(String username);

	int insertUser(User user);

	List<User> queryAllUser();

	void updateLogintimeByUsername(String username);

	User queryUserByUserId(String id);
	
}